title: BoSSS Documentation
description: BoSSS Framework Documentation

theme: just-the-docs

url: "https://ahmedmonzer8001-pixel.github.io"
baseurl: "/BoSSS_Doc.github.io"

search_enabled: true
heading_anchors: true

# Make docs a collection so Just the Docs builds a sidebar
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true
