title: BoSSS Documentation
description: BoSSS Framework Documentation

url: "https://ahmedmonzer8001-pixel.github.io"
baseurl: "/BoSSS_Doc.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true
