title: BoSSS Documentation
description: BoSSS Framework Documentation

theme: just-the-docs

url: "https://ahmedmonzer8001-pixel.github.io"
baseurl: "/BoSSS_Doc.github.io"

search_enabled: true
heading_anchors: true

collections:
  docs:
    output: true
    permalink: /:collection/:path/

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true
